"""
JARVIS response object.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from .status import ResponseStatus


@dataclass(frozen=True, slots=True)
class Response:
    """
    Represents a response generated by JARVIS.
    """

    text: str

    status: ResponseStatus = (
        ResponseStatus.SUCCESS
    )

    data: object | None = field(
        default=None,
    )