"""
JARVIS response object.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Response:
    """
    Represents a response generated by JARVIS.
    """

    text: str